# Generated by Django 4.2.20 on 2025-04-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("siteid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="entity",
            name="image",
            field=models.CharField(
                default="static_images/PCSSymbol.png", max_length=100
            ),
        ),
    ]
