# Generated by Django 4.2.20 on 2025-04-18 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_site_entity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.site"
            ),
        ),
    ]
