# Generated by Django 4.2.20 on 2025-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_entity_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
    ]
