# Generated by Django 4.2.20 on 2025-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_personnel_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="image",
            field=models.ImageField(
                default="entitypfp/default_image.png", upload_to="entitypfp/"
            ),
        ),
    ]
