# Generated by Django 4.2.20 on 2025-04-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_entity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="quote",
            field=models.CharField(default="Silenced.", max_length=100),
        ),
    ]
