# Generated by Django 4.2.20 on 2025-04-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_user_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="userpfp/default_image.png", upload_to="userpfp/"
            ),
        ),
    ]
