# Generated by Django 4.2.20 on 2025-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="description",
            field=models.TextField(blank=True, default="No description provided."),
        ),
        migrations.AlterField(
            model_name="entity",
            name="image",
            field=models.ImageField(
                blank=True,
                default="entitypfp/default_image.png",
                upload_to="entitypfp/",
            ),
        ),
    ]
