# Generated by Django 4.2.20 on 2025-04-19 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_entity_description_alter_entity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exp",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
