# Generated by Django 5.1.7 on 2025-04-19 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_bio_user_date_joined_user_entities_documented'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
